{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "7d4e6431-7a38-4c4e-9ed5-2568ec47aff4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting mysql-connector\n",
      "  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)\n",
      "     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--\n",
      "     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--\n",
      "     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--\n",
      "     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--\n",
      "     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--\n",
      "     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--\n",
      "      --------------------------------------- 0.3/11.9 MB ? eta -:--:--\n",
      "      --------------------------------------- 0.3/11.9 MB ? eta -:--:--\n",
      "      --------------------------------------- 0.3/11.9 MB ? eta -:--:--\n",
      "      --------------------------------------- 0.3/11.9 MB ? eta -:--:--\n",
      "      --------------------------------------- 0.3/11.9 MB ? eta -:--:--\n",
      "      --------------------------------------- 0.3/11.9 MB ? eta -:--:--\n",
      "      --------------------------------------- 0.3/11.9 MB ? eta -:--:--\n",
      "      --------------------------------------- 0.3/11.9 MB ? eta -:--:--\n",
      "     - ------------------------------------- 0.5/11.9 MB 163.1 kB/s eta 0:01:10\n",
      "     - ------------------------------------- 0.5/11.9 MB 163.1 kB/s eta 0:01:10\n",
      "     - ------------------------------------- 0.5/11.9 MB 163.1 kB/s eta 0:01:10\n",
      "     - ------------------------------------- 0.5/11.9 MB 163.1 kB/s eta 0:01:10\n",
      "     - ------------------------------------- 0.5/11.9 MB 163.1 kB/s eta 0:01:10\n",
      "     - ------------------------------------- 0.5/11.9 MB 163.1 kB/s eta 0:01:10\n",
      "     -- ------------------------------------ 0.8/11.9 MB 173.6 kB/s eta 0:01:04\n",
      "     -- ------------------------------------ 0.8/11.9 MB 173.6 kB/s eta 0:01:04\n",
      "     -- ------------------------------------ 0.8/11.9 MB 173.6 kB/s eta 0:01:04\n",
      "     -- ------------------------------------ 0.8/11.9 MB 173.6 kB/s eta 0:01:04\n",
      "     --- ----------------------------------- 1.0/11.9 MB 200.1 kB/s eta 0:00:54\n",
      "     --- ----------------------------------- 1.0/11.9 MB 200.1 kB/s eta 0:00:54\n",
      "     --- ----------------------------------- 1.0/11.9 MB 200.1 kB/s eta 0:00:54\n",
      "     ---- ---------------------------------- 1.3/11.9 MB 228.7 kB/s eta 0:00:47\n",
      "     ---- ---------------------------------- 1.3/11.9 MB 228.7 kB/s eta 0:00:47\n",
      "     ---- ---------------------------------- 1.3/11.9 MB 228.7 kB/s eta 0:00:47\n",
      "     ---- ---------------------------------- 1.3/11.9 MB 228.7 kB/s eta 0:00:47\n",
      "     ----- --------------------------------- 1.6/11.9 MB 248.3 kB/s eta 0:00:42\n",
      "     ----- --------------------------------- 1.6/11.9 MB 248.3 kB/s eta 0:00:42\n",
      "     ------ -------------------------------- 1.8/11.9 MB 270.3 kB/s eta 0:00:38\n",
      "     ------ -------------------------------- 1.8/11.9 MB 270.3 kB/s eta 0:00:38\n",
      "     ------ -------------------------------- 1.8/11.9 MB 270.3 kB/s eta 0:00:38\n",
      "     ------ -------------------------------- 1.8/11.9 MB 270.3 kB/s eta 0:00:38\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: There was an error checking the latest version of pip.\n",
      "ERROR: Exception:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_vendor\\urllib3\\response.py\", line 438, in _error_catcher\n",
      "    yield\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_vendor\\urllib3\\response.py\", line 561, in read\n",
      "    data = self._fp_read(amt) if not fp_closed else b\"\"\n",
      "           ~~~~~~~~~~~~~^^^^^\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_vendor\\urllib3\\response.py\", line 527, in _fp_read\n",
      "    return self._fp.read(amt) if amt is not None else self._fp.read()\n",
      "           ~~~~~~~~~~~~~^^^^^\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_vendor\\cachecontrol\\filewrapper.py\", line 102, in read\n",
      "    self.__buf.write(data)\n",
      "    ~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\tempfile.py\", line 499, in func_wrapper\n",
      "    return func(*args, **kwargs)\n",
      "OSError: [Errno 28] No space left on device\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 105, in _run_wrapper\n",
      "    status = _inner_run()\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 96, in _inner_run\n",
      "    return self.run(options, args)\n",
      "           ~~~~~~~~^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_internal\\cli\\req_command.py\", line 68, in wrapper\n",
      "    return func(self, options, args)\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_internal\\commands\\install.py\", line 387, in run\n",
      "    requirement_set = resolver.resolve(\n",
      "        reqs, check_supported_wheels=not options.target_dir\n",
      "    )\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_internal\\resolution\\resolvelib\\resolver.py\", line 96, in resolve\n",
      "    result = self._result = resolver.resolve(\n",
      "                            ~~~~~~~~~~~~~~~~^\n",
      "        collected.requirements, max_rounds=limit_how_complex_resolution_can_be\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_vendor\\resolvelib\\resolvers\\resolution.py\", line 515, in resolve\n",
      "    state = resolution.resolve(requirements, max_rounds=max_rounds)\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_vendor\\resolvelib\\resolvers\\resolution.py\", line 388, in resolve\n",
      "    self._add_to_criteria(self.state.criteria, r, parent=None)\n",
      "    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_vendor\\resolvelib\\resolvers\\resolution.py\", line 141, in _add_to_criteria\n",
      "    if not criterion.candidates:\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_vendor\\resolvelib\\structs.py\", line 194, in __bool__\n",
      "    return bool(self._sequence)\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_internal\\resolution\\resolvelib\\found_candidates.py\", line 163, in __bool__\n",
      "    self._bool = any(self)\n",
      "                 ~~~^^^^^^\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_internal\\resolution\\resolvelib\\found_candidates.py\", line 147, in <genexpr>\n",
      "    return (c for c in iterator if id(c) not in self._incompatible_ids)\n",
      "                       ^^^^^^^^\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_internal\\resolution\\resolvelib\\found_candidates.py\", line 37, in _iter_built\n",
      "    candidate = func()\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_internal\\resolution\\resolvelib\\factory.py\", line 187, in _make_candidate_from_link\n",
      "    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(\n",
      "                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n",
      "        link, template, name, version\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_internal\\resolution\\resolvelib\\factory.py\", line 233, in _make_base_candidate_from_link\n",
      "    self._link_candidate_cache[link] = LinkCandidate(\n",
      "                                       ~~~~~~~~~~~~~^\n",
      "        link,\n",
      "        ^^^^^\n",
      "    ...<3 lines>...\n",
      "        version=version,\n",
      "        ^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_internal\\resolution\\resolvelib\\candidates.py\", line 306, in __init__\n",
      "    super().__init__(\n",
      "    ~~~~~~~~~~~~~~~~^\n",
      "        link=link,\n",
      "        ^^^^^^^^^^\n",
      "    ...<4 lines>...\n",
      "        version=version,\n",
      "        ^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_internal\\resolution\\resolvelib\\candidates.py\", line 159, in __init__\n",
      "    self.dist = self._prepare()\n",
      "                ~~~~~~~~~~~~~^^\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_internal\\resolution\\resolvelib\\candidates.py\", line 236, in _prepare\n",
      "    dist = self._prepare_distribution()\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_internal\\resolution\\resolvelib\\candidates.py\", line 317, in _prepare_distribution\n",
      "    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_internal\\operations\\prepare.py\", line 532, in prepare_linked_requirement\n",
      "    return self._prepare_linked_requirement(req, parallel_builds)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_internal\\operations\\prepare.py\", line 603, in _prepare_linked_requirement\n",
      "    local_file = unpack_url(\n",
      "        link,\n",
      "    ...<4 lines>...\n",
      "        hashes,\n",
      "    )\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_internal\\operations\\prepare.py\", line 174, in unpack_url\n",
      "    file = get_http_url(\n",
      "        link,\n",
      "    ...<2 lines>...\n",
      "        hashes=hashes,\n",
      "    )\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_internal\\operations\\prepare.py\", line 115, in get_http_url\n",
      "    from_path, content_type = download(link, temp_dir.path)\n",
      "                              ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_internal\\network\\download.py\", line 185, in __call__\n",
      "    bytes_received = self._process_response(\n",
      "        resp, link, content_file, 0, total_length\n",
      "    )\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_internal\\network\\download.py\", line 208, in _process_response\n",
      "    return self._write_chunks_to_file(\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~^\n",
      "        chunks, content_file, allow_partial=bool(total_length)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_internal\\network\\download.py\", line 218, in _write_chunks_to_file\n",
      "    for chunk in chunks:\n",
      "                 ^^^^^^\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_internal\\cli\\progress_bars.py\", line 61, in _rich_download_progress_bar\n",
      "    for chunk in iterable:\n",
      "                 ^^^^^^^^\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_internal\\network\\utils.py\", line 65, in response_chunks\n",
      "    for chunk in response.raw.stream(\n",
      "                 ~~~~~~~~~~~~~~~~~~~^\n",
      "        chunk_size,\n",
      "        ^^^^^^^^^^^\n",
      "    ...<22 lines>...\n",
      "        decode_content=False,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^\n",
      "    ):\n",
      "    ^\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_vendor\\urllib3\\response.py\", line 622, in stream\n",
      "    data = self.read(amt=amt, decode_content=decode_content)\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_vendor\\urllib3\\response.py\", line 560, in read\n",
      "    with self._error_catcher():\n",
      "         ~~~~~~~~~~~~~~~~~~~^^\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\contextlib.py\", line 162, in __exit__\n",
      "    self.gen.throw(value)\n",
      "    ~~~~~~~~~~~~~~^^^^^^^\n",
      "  File \"C:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\pip\\_vendor\\urllib3\\response.py\", line 455, in _error_catcher\n",
      "    raise ProtocolError(\"Connection broken: %r\" % e, e)\n",
      "pip._vendor.urllib3.exceptions.ProtocolError: (\"Connection broken: OSError(28, 'No space left on device')\", OSError(28, 'No space left on device'))\n"
     ]
    }
   ],
   "source": [
    "pip install mysql-connector"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "475d6353-c3d6-4677-997e-b36add23589d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
